Repository JuliaPackaging/BinaryBuilderBase.jl, pull requests merged in 2024-12, with the labels that each got.

#393 [Runner] Fix glibc version of x86 architectures
  src/Runner.jl
Labels: runner :running_woman:

#396 Skip Rust tests with unprivileged runners and unpacked shards
  test/runners.jl
Labels: toolchain :wrench: :chains:, rust :crab:

#375 Support riscv64 platform
  Artifacts.toml
  Project.toml
  src/BinaryBuilderBase.jl
  src/BuildToolchains.jl
  src/Platforms.jl
  src/Rootfs.jl
  src/Runner.jl
  src/riscv64.jl
  test/platforms.jl
  test/rootfs.jl
  test/runners.jl
Labels: enhancement, toolchain :wrench: :chains:, risc-v :five:

#397 Add Rust 1.83.0 toolchain
  Artifacts.toml
Labels: toolchain :wrench: :chains:, rust :crab:

#399 Allow specifying a Rust and Go toolchain version for the build
  Project.toml
  src/Rootfs.jl
  test/rootfs.jl
Labels: rust :crab:
